[DEFAULT]
cpu_allocation_ratio = 16.0
ram_allocation_ratio = 4.0
disk_allocation_ratio = 4.0
[vnc]
novncproxy_base_url = https://vip.public.cloud:6080/vnc.html
[pci]
device_spec = [{"vendor_id": "10de", "product_id": "27b2"}]



#[libvirt]
#cpu_mode = custom
#cpu_model = Broadwell-noTSX
