[DEFAULT]
#cpu_allocation_ratio = 8.0
#ram_allocation_ratio = 2.0
#disk_allocation_ratio = 1.0

enabled_mdev_types = nvidia-476

[devices]
enabled_mdev_types = nvidia-476

[mdev_nvidia-476]
device_addresses = 0000:ab:00.0
