[DEFAULT]
#cpu_allocation_ratio = 8.0
#ram_allocation_ratio = 2.0
#disk_allocation_ratio = 1.0

[quota]
instances = 20
cores = 40
ram = 409600

[pci]
alias = {"vendor_id": "10de", "product_id": "27b2", "device_type": "type-PCI", "name": "rtx4000ada"}



