[quotas]
quota_network = 1000
quota_subnet = 1000
quota_port = 5000
quota_driver = neutron.db.quota.driver_nolock.DbQuotaNoLockDriver
track_quota_usage = true
quota_router = 100
quota_floatingip = 500
quota_security_group = 100
quota_security_group_rule = 1000
quota_rbac_policy=200
