[DEFAULT]
use_default_quota_class = True
default_volume_type = default-volume


#[ceph-rbd-production]
#volume_driver = cinder.volume.drivers.rbd.RBDDriver
#rbd_pool = ssd-no-replica  # or a specific pool like volumes-production
#rbd_ceph_conf = /etc/ceph/ceph.conf
#rbd_user = cinder
#backend_host = rbd-production
#volume_backend_name = rbd-production
#availability_zone = nova_production

