[DEFAULT]
use_default_quota_class = True
default_volume_type = default-volume
osapi_volume_workers = 16
executor_thread_pool_size = 1024

[database]
max_pool_size = 50
max_overflow = 30

[oslo_messaging_rabbit]
rpc_conn_pool_size = 64
