[DEFAULT]
periodic_interval_max = 60
[drivers]
openstack_ca_file = /etc/magnum/openstack_ca.crt
verify_ca = false
verify_ssl = false
ca_file = /etc/magnum/openstack_ca.crt 
[cluster]
nodes_affinity_policy = anti-affinity

[database]
max_pool_size = 100 
[capi_helm]
enabled = true
verify_ca = false
verify_ssl = false
[magnum_client]
ca_file = /etc/magnum/openstack_ca.crt
#[capi_helm]
#kubeconfig_file = /etc/magnum/kubeconfig
